name: docker

on:
  pull_request:
    paths:
      - Dockerfile

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - run: docker build . --build-arg PROXY_UNOPTIMIZED=1
