name: docker

on:
  pull_request:
    paths:
      - Dockerfile
      - rust-toolchain
      - justfile
      - .github/workflows/docker.yml

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: linkerd/dev/actions/setup-tools@v38
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - run: just docker
