name: docker

on:
  pull_request:
    paths:
      - Dockerfile

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - run: docker build . --build-arg PROXY_UNOPTIMIZED=1
